# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_auto_20180325_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipping',
            options={'managed': True, 'ordering': ['fk_id']},
        ),
    ]
